(function () {
  'use strict';
  var DATA_URL = 'data/vegetarian-restaurants.json';
  var CITY_ORDER = ['Beijing','Shanghai','Guangzhou','Shenzhen','Hangzhou','Chengdu','Nanjing','Suzhou','Wuhan','Xi’an'];
  var CATEGORY_LABELS = {fully_vegetarian:'Fully vegetarian',fully_vegan:'Fully vegan',buddhist_vegetarian:'Buddhist vegetarian',plant_based:'Plant-based'};
  var restaurants = [];
  var visibleLimit = window.matchMedia('(max-width:700px)').matches ? 6 : 10;
  var state = {query:'',city:'',category:''};
  var $ = function(s,root){return (root||document).querySelector(s);};
  var $$ = function(s,root){return Array.prototype.slice.call((root||document).querySelectorAll(s));};
  function escapeHtml(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
  function normalize(v){return String(v||'').normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim();}
  function fillSelect(select, values, firstLabel, labels){select.innerHTML='<option value="">'+escapeHtml(firstLabel)+'</option>'+values.map(function(v){return '<option value="'+escapeHtml(v)+'">'+escapeHtml(labels&&labels[v]||v)+'</option>';}).join('');}
  function haystack(r){return normalize([r.restaurantNameEnglish,r.restaurantNameChinese,r.city,r.dietaryCategoryLabel,r.dietaryCategory,'素食 纯素 vegan vegetarian plant based'].join(' '));}
  function filtered(){var words=normalize(state.query).split(' ').filter(Boolean);return restaurants.filter(function(r){if(words.length&&!words.every(function(w){return haystack(r).indexOf(w)!==-1;}))return false;if(state.city&&r.city!==state.city)return false;if(state.category&&r.dietaryCategory!==state.category)return false;return true;});}
  function leafIcon(){return '<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M50 12C31 13 18 23 16 39c-1 8 4 13 11 13 17 0 26-18 23-40Z"/><path d="M17 50c7-12 15-20 28-28"/><path d="M28 33c0 7 2 12 7 16"/></svg>';}
  function categoryClass(c){return c==='fully_vegan'?'vf-vegan':c==='buddhist_vegetarian'?'vf-buddhist':c==='plant_based'?'vf-plant':'vf-vegetarian';}
  function mapAction(r){var options={nameEnglish:r.restaurantNameEnglish,nameChinese:r.restaurantNameChinese,city:r.city,amapSearchQuery:r.amapSearchQuery,amapUrl:r.amapUrl,mode:r.buttonType==='open_amap'?'exact':'search'};if(window.MapLinks&&typeof window.MapLinks.renderChooser==='function')return window.MapLinks.renderChooser(options,{buttonClass:'btn sm hf-map-link'});return '<a class="btn sm hf-map-link" href="'+escapeHtml(r.amapUrl)+'" target="_blank" rel="noopener noreferrer">Open in AMap Global</a>';}
  function card(r){return '<article class="hf-card hf-card--compact vf-card"><div class="hf-card-icon">'+leafIcon()+'</div><div class="hf-card-main"><div class="hf-card-topline"><span>'+escapeHtml(r.city)+'</span><span class="hf-confidence '+escapeHtml(r.confidenceLevel)+'">'+escapeHtml(r.confidenceLevel)+'</span></div><h3>'+escapeHtml(r.restaurantNameEnglish)+'</h3><p class="hf-cn-name" lang="zh-CN">'+escapeHtml(r.restaurantNameChinese)+'</p><div class="hf-badges"><span class="'+categoryClass(r.dietaryCategory)+'">'+escapeHtml(r.dietaryCategoryLabel)+'</span><span>'+(r.buttonType==='open_amap'?'Exact place verified':'Map search prepared')+'</span></div><p class="hf-card-check">Confirm current branch details and ingredients before visiting.</p></div><div class="hf-card-actions hf-card-actions--compact"><a class="btn sm teal vf-detail-link" href="vegetarian-food/restaurants/'+encodeURIComponent(r.slug)+'/">View details</a>'+mapAction(r)+'</div></article>';}
  function saveState(){try{sessionStorage.setItem('vegetarianFinderState',JSON.stringify(state));}catch(_){}}
  function syncUrl(){var p=new URLSearchParams();Object.keys(state).forEach(function(k){if(state[k])p.set(k,state[k]);});history.replaceState(null,'',window.location.pathname+(p.toString()?'?'+p.toString():'')+'#finder');}
  function render(){var matches=filtered(),shown=matches.slice(0,visibleLimit);$('#vf-results').setAttribute('aria-busy','false');$('#vf-result-count').textContent=matches.length+(matches.length===1?' restaurant':' restaurants')+' found';$('#vf-clear-search').hidden=!state.query;$('#vf-results').innerHTML=matches.length?shown.map(card).join(''):'<div class="hf-empty"><strong>No matches yet.</strong><p>Try another city, food type or Chinese name.</p></div>';$('#vf-show-more').hidden=shown.length>=matches.length;$('#vf-show-more').textContent='Show more ('+(matches.length-shown.length)+' remaining)';$$('.vf-detail-link').forEach(function(a){a.addEventListener('click',saveState);});}
  function sync(){state.query=$('#vf-search').value.trim();state.city=$('#vf-city').value;state.category=$('#vf-category').value;visibleLimit=window.matchMedia('(max-width:700px)').matches?6:10;syncUrl();render();}
  function reset(){state={query:'',city:'',category:''};$('#vf-search').value='';$('#vf-city').value='';$('#vf-category').value='';visibleLimit=window.matchMedia('(max-width:700px)').matches?6:10;syncUrl();render();}
  function initControls(){fillSelect($('#vf-city'),CITY_ORDER,'All ten cities');fillSelect($('#vf-category'),Object.keys(CATEGORY_LABELS),'All food types',CATEGORY_LABELS);var params=new URLSearchParams(location.search);state.query=params.get('query')||'';state.city=params.get('city')||'';state.category=params.get('category')||'';$('#vf-search').value=state.query;$('#vf-city').value=state.city;$('#vf-category').value=state.category;$('#vf-search').addEventListener('input',sync);$('#vf-city').addEventListener('change',sync);$('#vf-category').addEventListener('change',sync);$('#vf-reset').addEventListener('click',reset);$('#vf-clear-search').addEventListener('click',function(){$('#vf-search').value='';sync();$('#vf-search').focus();});$('#vf-show-more').addEventListener('click',function(){visibleLimit+=10;render();});}
  function initNav(){var b=$('.nav-burger'),l=$('#nav-links');if(!b||!l)return;b.addEventListener('click',function(){var o=l.classList.toggle('open');b.setAttribute('aria-expanded',o?'true':'false');b.textContent=o?'×':'☰';});}
  fetch(DATA_URL,{cache:'no-store'}).then(function(res){if(!res.ok)throw new Error('Data request failed');return res.json();}).then(function(data){restaurants=Array.isArray(data.restaurants)?data.restaurants:[];restaurants.sort(function(a,b){var c=CITY_ORDER.indexOf(a.city)-CITY_ORDER.indexOf(b.city);return c||a.restaurantNameEnglish.localeCompare(b.restaurantNameEnglish);});initControls();render();}).catch(function(err){$('#vf-results').setAttribute('aria-busy','false');$('#vf-results').innerHTML='<div class="hf-empty"><strong>The directory could not load.</strong><p>Please refresh the page.</p></div>';$('#vf-result-count').textContent='Directory unavailable';var a=$('#vf-data-alert');a.hidden=false;a.textContent='Restaurant data could not be loaded.';console.error(err);});
  initNav();
})();
